terraform-ibm-modules/terraform-ibm-client-to-site-vpn

.github/settings.yml, tests/go.mod
Updated .github/settings.yml  to add the core-team topic to the repo.
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.
Your notes help the merger write the commit message for the PR that is published in the release notes for the module.
Run the CI pipeline when the PR is ready for …
=> Add core-team topic

.github/settings.yml
add more topics
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.
Your notes help the merger write the commit message for the PR that is published in the release notes for the module.
Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the …
=> docs: add more topics

README.md, examples/highavailability_mode/version.tf, examples/landing-zone/version.tf, module-metadata.json, version.tf
Bump provider version to pick up bug fix for auth policies in 1.54.0
Update IBM provider to v1.54.0
```
/run pipeline
```
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of …
=> fix: upgrade provider to 1.54.0

cra-tf-validate-ignore-rules.json
update cra-tf-validate-ignore-rules.json to unblock pipeline
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.
Your notes help the merger write the commit message for the PR that is published in the release notes for the module.
Run the CI pipeline when the PR is ready for review and you …
=> ci: update cra-tf-validate-ignore-rules.json

tests/scripts/pre-validation-slz-vpc.sh
PR to update the prefix used in pre-validation script. Current prefix fails with:
```
│ Prefix must begin with a lowercase letter and contain only lowercase
│ letters, numbers, and - characters. Prefixes must end with a lowercase
+ numeric     = true
+ result      = (known after apply)
│ letter or number and be 16 or fewer characters.
│ 
│ This was checked by the validation rule at
│ .terraform/modules/landing_zone/patterns/vpc/module/variables.tf:15,3-13.
+ special     = false
+ upper       = false
}
```
If a release is required, replace this text with information that users need to know about the …
=> ci: update the prefix used in pre-validation script

.secrets.baseline, ibm_catalog.json
NOTE: The PR shows many changes to the json, however I just ran it through a json formatter and hence it shows as alot as changes, where really these are the only code updates:
- added missing dependencies section
- Fixed the diagram url
- Added a usage
```
/run pipeline
```
- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, …
=> fix: add missing dependencies section from catalog json

extensions/landing-zone/variables.tf
=> fix: update the existing_subnet_names variable description

.catalog-onboard-pipeline.yaml, .releaserc, tests/scripts/post-validation-slz-vpc.sh, tests/scripts/pre-validation-slz-vpc.sh
onboard to new catalog pipeline
```
/run pipeline
```
=> onboard to new catalog pipeline

ibm_catalog.json
=> Add provider name to ibm_catalog.json

.github/settings.yml
=> Add "deployable-architecture" topic

.catalog-onboard-pipeline.yaml, ibm_catalog.json
Update to `deploy-arch-ibm-client-to-site-vpn` since old proposed name was rejected:
```
/run pipeline
```
=> Updated DA programmatic name

extensions/landing-zone/README.md, ibm_catalog.json
Update links to tutorial in Cloud docs to point to landing zone deployment guide
```
/run pipeline
```
=> Update link to Cloud docs

.catalog-onboard-pipeline.yaml
=> Update .catalog-onboard-pipeline.yaml to mark DA as ready on import to catalog

examples/ha-complete/main.tf
One resource wasn't checking if an existing SM instance is being passed in in ha-complete test.
```
/run pipeline
```
=> test: actually re-use SM instance

.catalog-onboard-pipeline.yaml, tests/scripts/pre-validation-slz-vpc.sh
=> chore: fix pre-validation script by using argument

ibm_catalog.json, tests/scripts/post-validation-slz-vpc.sh
=> chore: destroy tf_vars_file inside post-valdiations script

ibm_catalog.json, solutions/quickstart/variables.tf, solutions/standard/variables.tf
Added descriptions for the prefix in the ibm_catalog.json file and updated the description for the prefix variable in the  variable.tf file within the DA's.
Git_issue:[#11959](https://github.ibm.com/GoldenEye/issues/issues/11959)
```
/run pipeline
```
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub …
=> modified prefix description

solutions/quickstart/README.md, solutions/standard/README.md
fix the diagram links in the DA readmes
```
/run pipeline
```
=> docs: fix the diagram links in the DA readmes

ibm_catalog.json
=> fix: expose provider visibility

solutions/fully-configurable/variables.tf
=> chore: update DA to allow null for existing_resource_group_name input

ibm_catalog.json, tests/resources/main.tf
issue : https://github.ibm.com/GoldenEye/issues/issues/15895
Start to consume catalog feature that supports picking default resource group. The catalog team have added logic to the resource group picker so that if user selects "Default" from the dropdown, even if it is not named "Default", the picker will pass the actual name of the default resource group in the account to Schematics.
```
/run pipeline
```
- Use a conventional commit message to set the release level. Follow the …
=> chore: update existing_resource_group_name variable format and catalog entries
